makepkg: allow architecture-restricted split package building

diff --git a/scripts/libmakepkg/lint_pkgbuild/arch.sh.in b/scripts/libmakepkg/lint_pkgbuild/arch.sh.in
--- a/scripts/libmakepkg/lint_pkgbuild/arch.sh.in
+++ b/scripts/libmakepkg/lint_pkgbuild/arch.sh.in
@@ -30,52 +30,80 @@ source "$MAKEPKG_LIBRARY/util/pkgbuild.sh"
 lint_pkgbuild_functions+=('lint_arch')
 
 
-validate_arch() {
-	local n="$1"; shift
-	local a=("$@")
+validate_arch_entries() {
+	local arch=("$@")
 
-	if (( ${#a[@]} == 0 )); then
-		error "$(gettext "%s is not allowed to be empty.")" "arch"
-		ret=1
-	else
-		if in_array "any" "${a[@]}"; then
-			if (( ${#a[@]} != 1 )); then
-				error "$(gettext "Can not use '%s' architecture with other architectures")" "any"
-				ret=1
-			fi
-		else
-			if (( ! IGNOREARCH )); then
-				if ! in_array "$CARCH" "${a[@]}"; then
-					error "$(gettext "%s is not available for the '%s' architecture.")" "$n" "$CARCH"
-					ret=1
-				fi
-			fi
+	if in_array "any" "${arch[@]}"; then
+		if (( ${#arch[@]} != 1 )); then
+			error "$(gettext "Can not use '%s' architecture with other architectures")" "any"
+			ret=1
 		fi
-
-		for a in "${arch[@]}"; do
-			if [[ $a = *[![:alnum:]_]* ]]; then
-				error "$(gettext "%s contains invalid characters: '%s'")" \
-						'arch' "${a//[[:alnum:]_]}"
-				ret=1
-			fi
-		done
 	fi
 
 	if (( ${#arch[@]} != $(printf "%s\n" ${arch[@]} | sort -u | wc -l) )); then
 		error "$(gettext "%s can not contain duplicate values")" 'arch'
 		ret=1
 	fi
+
+	for a in "${arch[@]}"; do
+		if [[ $a = *[![:alnum:]_]* ]]; then
+			error "$(gettext "%s contains invalid characters: '%s'")" \
+					'arch' "${a//[[:alnum:]_]}"
+			ret=1
+		fi
+	done
+}
+
+validate_arch_global() {
+	if (( ${#arch[@]} == 0 )); then
+		error "$(gettext "%s is not allowed to be empty.")" "arch"
+		return 1
+	fi
+
+	validate_arch_entries "${arch[@]}"
+
+	if (( ! IGNOREARCH )) && ! in_array "$CARCH" "${arch[@]}" && ! in_array "any" "${arch[@]}"; then
+		error "$(gettext "%s is not available for the '%s' architecture.")" "$pkgbase" "$CARCH"
+		ret=1
+	fi
+
+	return $ret
+}
+
+validate_arch_override() {
+	local package="$1"
+	local override
+
+	get_pkgbuild_attribute "$package" 'arch' 1 override
+
+	if (( ${#override[@]} == 0 )); then
+		return 0
+	fi
+
+	validate_arch_entries "${override[@]}"
+
+	if in_array "any" "${override[@]}"; then
+		return $ret
+	fi
+
+	for o in "${override[@]}"; do
+		if ! in_array "$o" "${arch[@]}"; then
+			error "$(gettext "Overriden %s in package_%s() contains value not in global directive: '%s'")" "arch" "$package" "$o"
+			ret=1
+		fi
+	done
+
+	return $ret
 }
 
 lint_arch() {
-	local name list ret=0
+	local name ret=0
 
-	validate_arch "$pkgbase" "${arch[@]}"
+	validate_arch_global
 
 	if (( ret == 0 )); then
 		for name in "${pkgname[@]}"; do
-			get_pkgbuild_attribute "$name" 'arch' 1 list
-			validate_arch "$name" "${list[@]}"
+			validate_arch_override "$name"
 		done
 	fi
 
